name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:14.7-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: api_fitness_food_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:root@localhost:5432/api_fitness_food_test"
    steps:
    - uses: actions/checkout@v3

    - name: Install Ruby and gems
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.8
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle lock --add-platform x86_64-linux
        bundle install

    - name: Set up database schema
      run: bin/rails db:schema:load
      # run: rails db:migrate

    - name: Run Tests
      run: bundle exec rspec --format progress
